### ISSUE TITLE
[feature request] fuzzy select search

### ISSUE THREAD

**Issue by samuela** [fadeevab/cliclack#6]
a la https://github.com/junegunn/fzf, https://docs.rs/dialoguer/latest/dialoguer/struct.FuzzySelect.html, https://github.com/adelsz/inquirer-fuzzy-path, and so on

**Comment by cylewitruk** [comment]
This should be fairly easy to implement tbh -- we could stuff a crate like [strsim](https://crates.io/crates/strsim) behind a `fuzzy` feature and have a `with_fuzzy_search()` method on select/multiselect which exposes a text input on the first row allowing filtering... I don't need this, but I can understand it could be useful for larger lists. Just tossing in a comment while it was in my head :)

**Comment by antoinePutmans** [comment]
Hello guys, I wanted to have this kind of feature for a personal project. So I made this small feature that allow to filter the select items based on their label with an input
This might not be what you guys wanted because it is not implemented with fuzzy
This is what its looks like : 

https://github.com/fadeevab/cliclack/assets/113629846/9ba3bd81-99b7-44bc-a48e-c0c96b782adf

If you guys are interested in this feature, I would love to share the code with you 😃
I am new to open source so I dont know how it works to contribute and open a pull request for this project

**Comment by cylewitruk** [comment]
Welcome @antoinePutmans ! Lgtm in general, but agree with @fadeevab that the hint should be on the line after the promt. 

Not entirely clear from your snippet, but the list should also be limited in length (either configurable or using available terminal height) to avoid scrolling -- I think this might be missing in the current `select` impl but I don't recall off the top of my head -- but if filtering is needed then I will assume the list of available options is long 😊

I've been thinking of adding a similar feature for choosing github branches/tags in my use-case, so this legwork is definitely welcomed from my perspective!

**Comment by antoinePutmans** [comment]
Thank you guys for your feedback 🙂

@fadeevab yes, it will for sure look better ! 
@cylewitruk I will see if I can implement those feature

I'm still a beginner in Rust so I can't promise anything but I will try my best ! 😄

**Comment by cylewitruk** [comment]
> I'm still a beginner in Rust so I can't promise anything but I will try my best ! 😄

No worries, give it a try and we're here to help if you run into trouble. There's no better way to learn! 🙂

**Comment by fadeevab** [comment]
@antoinePutmans posted PR #47

**Comment by fadeevab** [comment]
Released in `cliclack v0.3.0`
